title: Sapatekno
email: sapatekno@gmail.com
author: Hadian Alkani
description: Personal blog of Hadian Alkani
url: 'http://www.sapatekno.com'
twitter_username: hadian_alkani
github_username: sapatekno
paginate: '4'
paginate_path: '/post/page/:num/'
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
